# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'VS2017-Win2016'
  name: Azure Pipelines
steps:
- script: 'npm install -g newman'
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Install Newman'

- task: BatchScript@1
  inputs:
    filename: 'BatchScripts\TestBatch.bat'
    arguments: 'PostmanTestEnv.postman_environment'
    workingFolder: '$(System.DefaultWorkingDirectory)'


- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFiles: '$(System.DefaultWorkingDirectory)\Results\*.xml'


